### ISSUE TITLE
Could not resolve hostname : Name or service not known

### ISSUE THREAD

**Issue by dipenpatel235** [olimpo88/PyDDNS#1]
hello @olimpo88  
here i have attached screenshot of my domain (growth.recipes) on aws route 53.

![1](https://user-images.githubusercontent.com/8135097/68921767-c71d4480-079f-11ea-9db9-318a38ec8cc2.png)

now i am doing ssh on that server `growth.recipes` and setup  ddns server as per steps given by you.
after done that i am open url "http://growth.recipes/" and login as admin user.

then i am adding subdomain name "mymachine"

Client side:

```
# /etc/ddclient.conf

protocol=dyndns2
use=if, if=wlp0s20f3
server=growth.recipes
login=admin
password='el@sadsadyS58'
mymachine.growth.recipes
```

then i have did router in port forwarding 80.

![3](https://user-images.githubusercontent.com/8135097/68923079-6bed5100-07a3-11ea-8a36-2c1734f0e6ee.png)

then i have setup in my local machine 192.168.1.126 nginx on port 80 and i am trying to open below url from browser `http://mymachine.growth.recipes`

let me know if anything is wrong.

**Comment by olimpo88** [comment]
Hi, the server seems to be running fine.

1- Within the panel you set up a subdomain mymachine.growth.recipes

2- Press the "update IP" button, to synchronize manually.

![foto569](https://user-images.githubusercontent.com/3307586/69332911-6629bc80-0c36-11ea-8883-65b71204c7da.jpg)


3- Test if from another pc you can solve your domain, from linux for example I would use this command:

dig mymachine.growth.recipes @ growth.recipes

dig domain @DNSSERVER

If this does not give an answer, it is because you need to open port 53, this port is for other external PCs to check the domains on your server.

**Comment by dipenpatel235** [comment]
root@dipen:~# dig mymachine.growth.recipes@growth.recipes
```
; <<>> DiG 9.11.3-1ubuntu1.10-Ubuntu <<>> mymachine.growth.recipes@growth.recipes
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 62216
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mymachine.growth.recipes\@growth.recipes. IN	A

;; Query time: 244 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Nov 21 18:06:26 IST 2019
;; MSG SIZE  rcvd: 63
```

**Comment by olimpo88** [comment]
missing a space before @

dig domain @dnsserver

**Comment by dipenpatel235** [comment]
```
root@dipen:~# dig mymachine.growth.recipes @growth.recipes

; <<>> DiG 9.11.3-1ubuntu1.10-Ubuntu <<>> mymachine.growth.recipes @growth.recipes
;; global options: +cmd
;; connection timed out; no servers could be reached
```

no firewall in my local client so port 53 is already open in local and growth.recipes server.

**Comment by olimpo88** [comment]
there is something strange

login to your server by ssh, on the same server run:

dig mymachine.growth.recipes @localhost

**Comment by olimpo88** [comment]
could you solve the problem of the DNS service that was not listening I was in port 53?

**Comment by dipenpatel235** [comment]
mine `docker-compose.yml` file configuration.
in that i have mapped port 54 with 53.
please verfify is that correct or not.

```
version: '2'
services:
  ddns:
    image: davd/docker-ddns:1.2.1
    restart: always
    environment:
      RECORD_TTL: 60
      ZONE: ddns.growth.recipes
      SHARED_SECRET: el@sadsadyS58
    ports:
      - "54:53"
      - "54:53/udp"
    volumes:
       - ./data/bind-data:/var/cache/bind
    networks:
      red:
  python:
    image: olimpo88/pyddns:latest
    restart: always
    volumes:
      - ./appdata/pyddns:/usr/src/app
      - ./appdata/static/node_modules:/usr/src/app/static/node_modules
    environment:
      DNS_HOST: d
      DNS_API_PORT: 8080
      DNS_DOMAIN: ddns.growth.recipes
      DNS_SHARED_SECRET: XXXXXXXXXXXXX
      DNS_ALLOW_AGENT: ddclient3,ddclient
      DB_HOST: postgres
      DB_NAME: pyddns
      DB_USER: pyddns
      DB_PASSWORD: XXXXXXXXXXXXX
      DJANGO_ADMIN_URL: administrator
      DJANGO_SU_NAME: admin
      DJANGO_SU_EMAIL: dipen.ec2010@gmail.com
      DJANGO_SU_PASSWORD: 1234
      OWN_ADMIN: 1
    depends_on:
      - "postgres"
    networks:
      red:

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: XXXXXXXXXXXXX
      POSTGRES_USER: pyddns
      POSTGRES_DB: pyddns
    volumes:
     - ./data/dbdata:/var/lib/postgresql/data
    networks:
      red:

  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - ./config/nginx_src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./appdata/static:/static
    depends_on:
      - "python"
    networks:
      red:
networks:
  red:
```
