### ISSUE TITLE
Problen config?

### ISSUE THREAD

**Issue by olimpo88** [olimpo88/PyDDNS#2]
> is that correct ?
> please verify.
> 
> ![1](https://user-images.githubusercontent.com/8135097/69723700-4287da00-1140-11ea-917f-796b685d4e54.png)

Hello @olimpo88 and @dipenpatel235 

I'm in the same situation and have tried this same setup without success.

In addition to the same difficulty setting up Route 53, in my case it seems that I have a problem with PyDDNS, as it never receives an answer on dig tests. See below the result:

```
 [centos@ip-172-31-38-166 ~]$ dig avmagrini.ddns.mydomain.com.br @ddns.mydomain.com.br

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> avmagrini.ddns.mydomain.com.br @ddns.mydomain.com.br
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 5393
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;avmagrini.ddns.mydomain.com.br.   IN      A

;; AUTHORITY SECTION:
ddns.mydomain.com.br.      86400   IN      SOA     localhost. root.localhost. 74 3600 900 604800 86400

;; Query time: 0 msec
;; SERVER: 18.228.211.80#53(18.228.211.80)
;; WHEN: Thu Nov 28 04:06:16 UTC 2019
;; MSG SIZE  rcvd: 106
```

The result is the same with the command "dig avmagrini.ddns.mydomain.com.br @localhost".
Bellow, my "docker-compose.yml" file:

```
version: '2'
services:
  ddns:
    image: davd/docker-ddns:1.2.1
    restart: always
    environment:
      RECORD_TTL: 60
      ZONE: ddns.mydomain.com.br
      SHARED_SECRET: el@sadsadyS58
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
       - ./data/bind-data:/var/cache/bind
    networks:
      red:
  python:
    image: olimpo88/pyddns:latest
    restart: always
    volumes:
      - ./appdata/pyddns:/usr/src/app
      - ./appdata/static/node_modules:/usr/src/app/static/node_modules
    environment:
      DNS_HOST: ddns
      DNS_API_PORT: 8080
      DNS_DOMAIN: ddns.mydomain.com.br
      DNS_SHARED_SECRET: el@sadsadyS58
      DNS_ALLOW_AGENT: ddclient3,ddclient
      DB_HOST: postgres
      DB_NAME: pyddns
      DB_USER: pyddns
      DB_PASSWORD: PyDyn@m1cDNSP0s
      DJANGO_ADMIN_URL: administrator
      DJANGO_SU_NAME: admin
      DJANGO_SU_EMAIL: admin@my.company
      DJANGO_SU_PASSWORD: 1234
      OWN_ADMIN: 1
    depends_on:
      - "postgres"
    networks:
      red:

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: PyDyn@m1cDNSP0s
      POSTGRES_USER: pyddns
      POSTGRES_DB: pyddns
    volumes:
     - ./data/dbdata:/var/lib/postgresql/data
    networks:
      red:

  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - ./config/nginx_src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./appdata/static:/static
    depends_on:
      - "python"
    networks:
      red:
networks:
  red:
```

I could not find any configuration errors and port 53 should be open for UDP and TCP protocols, but netstat shows port 53 listening only for UDP6 and TPC6 protocols (although I can connect to the server on port 53 with Telnet). Could you please help me?

![image](https://user-images.githubusercontent.com/58280688/69872869-6f99d100-1295-11ea-89b1-bf1c073e32e6.png)

Thanks!

_Originally posted by @avmagrini in https://github.com/olimpo88/PyDDNS/issues/1#issuecomment-559334642_
