### ISSUE TITLE
Is there any way to erase logs?

### ISSUE THREAD

**Issue by radiooscar2004** [olimpo88/PyDDNS#42]
Is there a way to remove all logs from the system? or remove old logs (week old)?

Thank you

**Comment by olimpo88** [comment]
Hi @radiooscar2004, if your problem is about space, you can configure the service in docker compose to have a maximum size and this will delete old logs

```
version: '2'
services:
  my_service:
    image: my_image
    logging:  # Adding logging configuration for this service
      driver: "json-file"
      options:
        max-size: "10m"  # Setting the maximum log size to 10 megabytes
```
